# Finetuning Config File

# Basic configuration
TUNE_HYPERPARAMS: true
INITIAL_WEIGHTS: null
DATASET: "rvi_mdb"
BASE_PATH: "."
EXPERIMENT_NAME: "optuna-uninitialized"
MAX_TRACE_LENGTH: 1000
MAX_TRACE_EXPANSION: 5

# Override specific fixed hyperparameters
FIXED_HYPERPARAMS:
  num_train_steps: 1000
  group_by_length: False
  eval_steps: 10
  logging_steps: 10

# Override tunable hyperparameters
DEFAULT_TUNABLE_HYPERPARAMS:
  learning_rate: 1e-3
  per_device_train_batch_size: 32
  weight_decay: 0.005
  warmup_steps: 100
  gradient_accumulation_steps: 1
  freeze_feature_encoder: true

SAMPLING_RATE: 200e6